import { ZoneConfig } from './types';

export const ZONES: ZoneConfig[] = [
  // --- LEVELS 1 to 5: EASY MODE (SYSTEM RECON & BOOTSTRAP) ---
  {
    levelNumber: 1,
    id: 'ZONE_1_STABLE',
    name: 'LEVEL 1: SYSTEM BOOT',
    tagline: 'Gentle Circuits • Wide Platforms • Basic Leaps',
    distanceStart: 0,
    distanceEnd: 320,
    baseSpeed: 205,
    minGap: 48,
    maxGap: 82,
    minPlatWidth: 180,
    maxPlatWidth: 290,
    hazardChance: 0.18,
    defaultWeather: 'Data Rain',
    difficultyRating: 'EASY',
    colorTheme: {
      primary: '#06b6d4',
      border: 'border-cyan-500/40',
      bg: 'bg-cyan-950/70',
      text: 'text-cyan-300',
    },
  },
  {
    levelNumber: 2,
    id: 'ZONE_2_HIGHWAY',
    name: 'LEVEL 2: DATA HIGHWAY',
    tagline: 'Bouncy Launchpads • Magnet Fields • Cache Collecting',
    distanceStart: 320,
    distanceEnd: 720,
    baseSpeed: 215,
    minGap: 52,
    maxGap: 90,
    minPlatWidth: 170,
    maxPlatWidth: 280,
    hazardChance: 0.22,
    defaultWeather: 'Data Rain',
    difficultyRating: 'EASY',
    colorTheme: {
      primary: '#10b981',
      border: 'border-emerald-500/40',
      bg: 'bg-emerald-950/70',
      text: 'text-emerald-300',
    },
  },
  {
    levelNumber: 3,
    id: 'ZONE_3_BUFFER',
    name: 'LEVEL 3: MEMORY BUFFER',
    tagline: 'Moving Data Blocks • Soft Lasers • Steady Pace',
    distanceStart: 720,
    distanceEnd: 1200,
    baseSpeed: 225,
    minGap: 56,
    maxGap: 96,
    minPlatWidth: 165,
    maxPlatWidth: 270,
    hazardChance: 0.26,
    defaultWeather: 'Static Fog',
    difficultyRating: 'EASY',
    colorTheme: {
      primary: '#f59e0b',
      border: 'border-amber-500/40',
      bg: 'bg-amber-950/70',
      text: 'text-amber-300',
    },
  },
  {
    levelNumber: 4,
    id: 'ZONE_4_APERTURE',
    name: 'LEVEL 4: FIREWALL APERTURE',
    tagline: 'Thermal Vents • Dual Paths • Shield Recovery',
    distanceStart: 1200,
    distanceEnd: 1750,
    baseSpeed: 235,
    minGap: 60,
    maxGap: 104,
    minPlatWidth: 160,
    maxPlatWidth: 260,
    hazardChance: 0.30,
    defaultWeather: 'Static Fog',
    difficultyRating: 'EASY',
    colorTheme: {
      primary: '#f43f5e',
      border: 'border-rose-500/40',
      bg: 'bg-rose-950/70',
      text: 'text-rose-300',
    },
  },
  {
    levelNumber: 5,
    id: 'ZONE_5_GATEWAY',
    name: 'LEVEL 5: GATEWAY SECTOR',
    tagline: 'Sector 1 Climax • Rapid Circuits • Gateway Breach',
    distanceStart: 1750,
    distanceEnd: 2350,
    baseSpeed: 245,
    minGap: 64,
    maxGap: 110,
    minPlatWidth: 155,
    maxPlatWidth: 250,
    hazardChance: 0.32,
    defaultWeather: 'Data Rain',
    difficultyRating: 'EASY (CLIMAX)',
    colorTheme: {
      primary: '#8b5cf6',
      border: 'border-violet-500/40',
      bg: 'bg-violet-950/70',
      text: 'text-violet-300',
    },
  },

  // --- LEVELS 6 to 10: HARD MODE (OVERCLOCK & CORRUPTED ANOMALY) ---
  {
    levelNumber: 6,
    id: 'ZONE_6_OVERCLOCK',
    name: 'LEVEL 6: OVERCLOCK NEXUS',
    tagline: 'High Velocity • Sweeping Lasers • Rapid Reflexes',
    distanceStart: 2350,
    distanceEnd: 3050,
    baseSpeed: 275,
    minGap: 78,
    maxGap: 132,
    minPlatWidth: 135,
    maxPlatWidth: 220,
    hazardChance: 0.48,
    defaultWeather: 'Glitch Storm',
    difficultyRating: 'HARD',
    colorTheme: {
      primary: '#d946ef',
      border: 'border-fuchsia-500/40',
      bg: 'bg-fuchsia-950/75',
      text: 'text-fuchsia-300',
    },
  },
  {
    levelNumber: 7,
    id: 'ZONE_7_CORRUPTION',
    name: 'LEVEL 7: CORRUPTED MATRIX',
    tagline: 'Crumbling Floors • Patrolling Sawblades • High Voltage',
    distanceStart: 3050,
    distanceEnd: 3850,
    baseSpeed: 290,
    minGap: 82,
    maxGap: 138,
    minPlatWidth: 125,
    maxPlatWidth: 210,
    hazardChance: 0.52,
    defaultWeather: 'Glitch Storm',
    difficultyRating: 'HARD',
    colorTheme: {
      primary: '#ea580c',
      border: 'border-orange-600/50',
      bg: 'bg-orange-950/80',
      text: 'text-orange-300',
    },
  },
  {
    levelNumber: 8,
    id: 'ZONE_8_VOID_ABYSS',
    name: 'LEVEL 8: THE VOID ABYSS',
    tagline: 'Disappearing Platforms • Tesla Arcs • Precision Leaps',
    distanceStart: 3850,
    distanceEnd: 4700,
    baseSpeed: 305,
    minGap: 86,
    maxGap: 144,
    minPlatWidth: 118,
    maxPlatWidth: 195,
    hazardChance: 0.55,
    defaultWeather: 'Static Fog',
    difficultyRating: 'HARD',
    colorTheme: {
      primary: '#14b8a6',
      border: 'border-teal-500/50',
      bg: 'bg-teal-950/80',
      text: 'text-teal-300',
    },
  },
  {
    levelNumber: 9,
    id: 'ZONE_9_CRITICAL',
    name: 'LEVEL 9: SYSTEM CRITICAL',
    tagline: 'Maximum Velocity • Relentless Drones • Falling Debris',
    distanceStart: 4700,
    distanceEnd: 5650,
    baseSpeed: 320,
    minGap: 88,
    maxGap: 148,
    minPlatWidth: 112,
    maxPlatWidth: 185,
    hazardChance: 0.58,
    defaultWeather: 'Glitch Storm',
    difficultyRating: 'HARD',
    colorTheme: {
      primary: '#e11d48',
      border: 'border-rose-600/60',
      bg: 'bg-rose-950/85',
      text: 'text-rose-400',
    },
  },
  {
    levelNumber: 10,
    id: 'ZONE_10_APEX_CORE',
    name: 'LEVEL 10: THE APEX GLITCH CORE',
    tagline: 'FINAL BOSS • 3-Phase Glitch Core • Ultimate Survival',
    distanceStart: 5650,
    distanceEnd: 6800,
    baseSpeed: 325,
    minGap: 82,
    maxGap: 136,
    minPlatWidth: 135,
    maxPlatWidth: 230,
    hazardChance: 0.38,
    defaultWeather: 'Glitch Storm',
    difficultyRating: 'HARD (FINAL BOSS)',
    colorTheme: {
      primary: '#ef4444',
      border: 'border-red-500/70',
      bg: 'bg-red-950/90',
      text: 'text-red-400',
    },
  },
];
